name: CovetGUIUtils
version: '1.0-SNAPSHOT'
main: gg.wrldmap.covetGUIUtils.CovetGUIUtils
bootstrapper: gg.wrldmap.covetGUIUtils.Bootstrapper
api-version: '1.21.11'
authors: [ wrldmap ]
description: Utilities for easy GUI creation.
folia-supported: true
website: https://covet.network
dependencies:
  server:
    ItemsAdder:
      load: BEFORE
      required: FALSE
    Oraxen:
      load: BEFORE
      required: FALSE
    Nexo:
      load: BEFORE
      required: FALSE
    Skript:
      load: BEFORE
      required: FALSE
    PlaceholderAPI:
      load: BEFORE
      required: TRUE